version: '3'
services:
  solr-server:
    container_name: solr-server 
    image: solr:8.0.0
    restart: unless-stopped
    ports:
      - 8983:8983
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - products
    networks:
      - solr
  solr-api:
    container_name: solr-api
    image: solr-api
    build: .
    restart: on-failure
    depends_on:
      - solr-server
    ports:
      - 8083:8080
    environment:
      - SPRING_DATA_SOLR_HOST=http://solr-server:8983/solr
    networks:
      - solr
volumes:
  data:
networks:
  solr:
    name: solr-network